services:
  nodecore:
    image: drpcorg/nodecore:latest
    container_name: nodecore
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config/nodecore.yml:/app/nodecore.yml
    networks:
      - nodecore-network

networks:
  nodecore-network:
    driver: bridge